title: Indie-Tracker
email: your-email@example.com

domain: artixzenevich.github.io       
url: https://artixzenevich.github.io  

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

vk: https://vk.com/indie_games_tracker
telegram: https://t.me/indie_tracker

# Дефолтные метаданные для постов в админке
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: post
      categories: ""
      image: "/covers/"
      release-date: ""
      genres: ""
      developer: ""
      publisher: ""
      type: "Лицензия"
      release: GOG
      language: русский, английский
      sound: отсутствует
      therapy: Не требуется (DRM-free)
      os: ""
      cpu: ""
      ram: ""
      gpu: ""
      space: ""
      download: "/downloads/file.torrent"
      steam: ""
      youtube: ""
      img1: ""
      img2: ""
      img3: ""
      img4: ""
      description: ""
      metacritic: ""

pagination:
  enabled: true
  per_page: 28
  permalink: '/page/:num/'
  title: 'страница - :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
